name = "xymake_daily"
main = "main.ts"
compatibility_date = "2025-04-04"
dev.port = 3000
routes = [
  { pattern = "daily.xymake.com", custom_domain = true }
]

# Daily schedule at 00:00 UTC
[triggers]
crons = ["0 0 * * *"] # Run once a day at midnight UTC

[[kv_namespaces]]
binding = "TWEET_KV"
id = "30fb3f9f94c64cf384786cc7ceb595a3"

[[queues.producers]]
queue = "xymake-queue"
binding = "xymake_queue"

[[queues.consumers]]
queue = "xymake-queue"